version: '3.4'

services:
  api:
    image: reservationscontainerregistry.azurecr.io/api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports: 
      - "80:80"
      - "5001:5001"
    depends_on: 
        - "reservations.testing.database"

  reservations.testing.database: 
     image: mcr.microsoft.com/mssql/server:2022-latest
     container_name: Reservations.Db
     volumes:
       - ./.containers/database:/var/opt/mssql/data
     ports:
       - "1433:1433"
     environment:
       ACCEPT_EULA: "Y"
       MSSQL_SA_PASSWORD: "SqlP@ssword"