apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: f54ef161-516c-4a1a-88fa-9f0e270b0514
    keyvaultName: reservationappkeyvault        
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: AZUREREDISCONNECTIONSTRING
          objectType: secret              
          objectVersion: ""               
        - |
          objectName: AZURESTORAGECONNECTIONSTRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBCONNECTIONSTRING
          objectType: secret
          objectVersion: ""
    tenantId: 2bac32fd-d9a2-40d9-a272-3a35920f5607                 